name: Deploy Next.js App to AWS EC2

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify your Node.js version


      - name: Create SSH key
        run: echo "${{ secrets.AWS_EC2_KEY }}" > ec2_key.pem && chmod 400 ec2_key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.AWS_EC2_HOST }}  # Your EC2 instance public IP or DNS
          username: ${{ secrets.AWS_EC2_USER }}  # Typically 'ubuntu' for Ubuntu instances
          key: ${{ secrets.AWS_EC2_KEY }}  # The SSH key stored in GitHub Secrets
          script: |
            # Navigate to the deployment directory
            cd /home/ubuntu/my-next-app
            
            # Pull the latest changes from the main branch
            git pull origin main
            
            # Install dependencies
            npm install
            
            # Build the application
            npm run build
            
            # Restart the application using PM2
            pm2 restart all  # Ensure PM2 is installed and managing your app
