name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH and connect to EC2 Instance
        env:
          HOST: ${{ secrets.AWS_EC2_HOST }}
          USER: ${{ secrets.AWS_EC2_USER }}
          PORT: ${{ secrets.EC2_PORT || 22 }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p $PORT $USER@$HOST << 'EOF'
            # Navigate to the project directory (create if not present)
            if [ ! -d "/home/ubuntu/my-next-app" ]; then
              mkdir -p /home/ubuntu/my-next-app
            fi
            cd /home/ubuntu/my-next-app

      # Pull the latest changes
      - name: upload the changes to instance
        run: |
            if [ ! -d "/home/ubuntu/my-next-app/.git" ]; then
              git clone https://github.com/infoirfank/github-action-pipeline.git /home/ubuntu/my-next-app
            fi
            cd /home/ubuntu/my-next-app
            git fetch origin main
            git reset --hard origin/main

      # Remove the old .next build
      - name: remove old build
        run: | 
            rm -rf .next

      # Install dependencies
      - name: install dependencies
        run: |
            npm install 

      # Build the application
      - name: Build the application 
        run: |
          npm run build

          # Install PM2 if it's not already installed
          #- name: Install PM2 if it's not already installed
          #  run: |
           #   npm install -g pm2
    
      # Start the Next.js application
      # Check if the app is already running and either restart or start
      - name: Start the Next.js application
        run: | 
          if pm2 describe my-next-app > /dev/null; then
            pm2 restart my-next-app
          else
            pm2 start npm --name "my-next-app" -- start
          fi
          pm2 save
          EOF
